export const Data = [
    {
        category:'dog',
        path:'./Images/Dog/1.jpg'
    },
    {
        category:'dog',
        path:'./Images/Dog/2.jpg'
    },
    {
        category:'dog',
        path:'./Images/Dog/3.jpg'
    },
    {
        category:'dog',
        path:'./Images/Dog/4.jpg'
    },
    {
        category:'dog',
        path:'./Images/Dog/5.jpg'
    },
    {
        category:'dog',
        path:'./Images/Dog/6.jpg'
    },
    {
        category:'dog',
        path:'./Images/Dog/7.jpg'
    },
    {
        category:'dog',
        path:'./Images/Dog/8.jpg'
    },
    {
        category:'dog',
        path:'./Images/Dog/9.jpg'
    },
    {
        category:'dog',
        path:'./Images/Dog/10.jpg'
    },
    {
        category:'dog',
        path:'./Images/Dog/11.jpg'
    },
    {
        category:'dog',
        path:'./Images/Dog/12.jpg'
    },
    {
        category:'cat',
        path:'./Images/Cat/1.jpg'
    },
    {
        category:'cat',
        path:'./Images/Cat/2.jpg'
    },
    {
        category:'cat',
        path:'./Images/Cat/3.jpg'
    },
    {
        category:'cat',
        path:'./Images/Cat/4.jpg'
    },
    {
        category:'cat',
        path:'./Images/Cat/5.jpg'
    },
    {
        category:'cat',
        path:'./Images/Cat/6.jpg'
    },
    {
        category:'cat',
        path:'./Images/Cat/7.jpg'
    },
    {
        category:'cat',
        path:'./Images/Cat/8.jpg'
    },
    {
        category:'cat',
        path:'./Images/Cat/9.jpg'
    },
    {
        category:'cat',
        path:'./Images/Cat/10.jpg'
    },
    {
        category:'cat',
        path:'./Images/Cat/11.jpg'
    },
    {
        category:'cat',
        path:'./Images/Cat/12.jpeg'
    },
    
]